---
output:
  pdf_document: default
---
```{r message=TRUE}
library(tidyverse)
# Run data wrangling files first ####
# Run limited service script
source(file = "limited_serv_wrangling.R", local = wrangled <- new.env())
# Run all industries script
source(file = "all_industries_data_wrangling.R", local = wrangled)

```

# Joining all industries and limited service ####


```{r message=TRUE}

joined <- new.env()
joined$data <- full_join(
  x = wrangled$min_wage$limited_increase,
  y = wrangled$all_ind_combined$gather) |> 
  mutate(
    proportion_limited = emplvl_limited / emplvl_all) |>
  # filter(proportion_limited > 0 & !is.infinite(proportion_limited)) |> 
  na.omit() |>
  mutate(
    area_fips = factor(area_fips)
  ) %>%
  filter(emplvl_limited > 0)

```
```{r}

#Setting up for 2011-2012

data_2011_2012 <- joined$data |> 
  filter(year_decimal %in% seq(2011.5,2012.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2011-2012

model_2011_2012 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2011_2012) 
```


```{r}

#Setting up for 2012-2013

data_2012_2013 <- joined$data |> 
  filter(year_decimal %in% seq(2012.5,2013.5, by = 1/12)) |> 
  mutate(year = as.factor(year)) #|> 
  # dummy_columns(
  #   select_columns = c('year_decimal', 'state'), 
  #   remove_first_dummy = TRUE, 
  # ) |> 
  # rename(post = year_2013, treat = state_MO)

```


```{r}

#Regression for 2012-2013

model_2012_2013 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2012_2013) 

```


```{r}

# Setting up for 2013 - 2014

data_2013_2014 <- joined$data |> 
  filter(year_decimal %in% seq(2013.5,2014.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2013 - 2014

model_2013_2014 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2013_2014) 

```


```{r}

# Setting up for 2014 - 2015

data_2014_2015 <- joined$data |> 
  filter(year_decimal %in% seq(2014.5,2015.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2014 - 2015

model_2014_2015 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2014_2015) 

```

```{r}

# Setting up for 2015 - 2016

data_2015_2016 <- joined$data |> 
  filter(year_decimal %in% seq(2015.5,2016.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2015 - 2016

model_2015_2016 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2015_2016) 

```

```{r}

# Setting up for 2016 - 2017

data_2016_2017 <- joined$data |> 
  filter(year_decimal %in% seq(2016.5,2017.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2016 - 2017

model_2016_2017 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2016_2017) 

```


```{r}

# Setting up for 2017 - 2018

data_2017_2018 <- joined$data |> 
  filter(year_decimal %in% seq(2017.5,2018.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2017 - 2018

model_2017_2018 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2017_2018) 

```


```{r}
# Setting up for 2018 - 2019

data_2018_2019 <- joined$data |> 
  filter(year_decimal %in% seq(2018.5,2019.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2018 - 2019

model_2018_2019 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2018_2019) 

```


```{r}

# Setting up for 2019 - 2020

data_2019_2020 <- joined$data |> 
  filter(year_decimal %in% seq(2019.5,2020.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2019 - 2020

model_2019_2020 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2019_2020) 

```


```{r}
# Setting up for 2020 - 2021

data_2020_2021 <- joined$data |> 
  filter(year_decimal %in% seq(2020.5,2021.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2020 - 2021

model_2020_2021 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2020_2021)

```

```{r}

# Setting up for 2021 - 2022

data_2021_2022 <- joined$data |> 
  filter(year_decimal %in% seq(2021.5,2022.5, by = 1/12)) |> 
  mutate(year = as.factor(year))

#Regression for 2021 - 2022

model_2021_2022 <- lm(formula = emplvl_limited ~ state * year + emplvl_all,
   data = data_2021_2022) 

```

```{r}
confint_model_2011_2012 <- confint(model_2011_2012)["stateMO:year2012",]
          
confint_model_2012_2013 <- confint(model_2012_2013)["stateMO:year2013",]

confint_model_2013_2014 <- confint(model_2013_2014)
confint_model_2014_2015 <- confint(model_2014_2015)
confint_model_2015_2016 <- confint(model_2015_2016)
confint_model_2016_2017 <- confint(model_2016_2017)
confint_model_2017_2018 <- confint(model_2017_2018)
confint_model_2018_2019 <- confint(model_2018_2019)
confint_model_2019_2020 <- confint(model_2019_2020)
confint_model_2020_2021 <- confint(model_2020_2021)
confint_model_2021_2022 <- confint(model_2021_2022)

```

```{r}

confints <- rbind(
"m_2012" = confint(model_2011_2012)["stateMO:year2012",], "m_2013" = confint(model_2012_2013)["stateMO:year2013",], "m_2014" = confint(model_2013_2014)["stateMO:year2014",], "m_2015" = confint(model_2014_2015)["stateMO:year2015",],
"m_2016" = confint(model_2015_2016)["stateMO:year2016",],
"m_2017" = confint(model_2016_2017)["stateMO:year2017",],
"m_2018" = confint(model_2017_2018)["stateMO:year2018",],
"m_2019" = confint(model_2018_2019)["stateMO:year2019",],
"m_2020" = confint(model_2019_2020)["stateMO:year2020",],
"m_2021" = confint(model_2020_2021)["stateMO:year2021",],
"m_2022" = confint(model_2021_2022)["stateMO:year2022",]
) %>% as.data.frame() %>%
  mutate(year = 2012:2022)

```


```{r}

# Compile coefficients into dataframe for visualizations

library(broom)

tidy_model_2011_2012 <- tidy(model_2011_2012) %>%
  filter(term %in% "stateMO:year2012") %>%
           select(term,estimate)

tidy_model_2012_2013 <- tidy(model_2012_2013) %>%
  filter(term %in% "stateMO:year2013") %>%
           select(term,estimate)


tidy_model_2013_2014 <- tidy(model_2013_2014) %>%
  filter(term %in% "stateMO:year2014") %>%
           select(term,estimate)

tidy_model_2014_2015 <- tidy(model_2014_2015) %>%
  filter(term %in% "stateMO:year2015") %>%
           select(term,estimate)

tidy_model_2015_2016 <- tidy(model_2015_2016) %>%
  filter(term %in% "stateMO:year2016") %>%
           select(term,estimate)

tidy_model_2016_2017 <- tidy(model_2016_2017) %>%
  filter(term %in% "stateMO:year2017") %>%
           select(term,estimate)

tidy_model_2017_2018 <- tidy(model_2017_2018) %>%
  filter(term %in% "stateMO:year2018") %>%
           select(term,estimate)

tidy_model_2018_2019 <- tidy(model_2018_2019) %>%
  filter(term %in% "stateMO:year2019") %>%
           select(term,estimate)

tidy_model_2019_2020 <- tidy(model_2019_2020) %>%
  filter(term %in% "stateMO:year2020") %>%
           select(term,estimate)

tidy_model_2020_2021 <- tidy(model_2020_2021) %>%
  filter(term %in% "stateMO:year2021") %>%
           select(term,estimate)

tidy_model_2021_2022 <- tidy(model_2021_2022) %>%
  filter(term %in% "stateMO:year2022") %>%
           select(term,estimate)
```

```{r}
#Adding all rows into one table

Coefficients_visualizations_table <- bind_rows("Model 2011 - 2012" = tidy_model_2011_2012, "Model 2012 - 2013" = tidy_model_2012_2013, "Model 2013 - 2014" = tidy_model_2013_2014, "Model 2014 - 2015" = tidy_model_2014_2015, "Model 2015 - 2016" = tidy_model_2015_2016, "Model 2016 - 2017" = tidy_model_2016_2017, "Model 2017 - 2018" = tidy_model_2017_2018, "Model 2018 - 2019" = tidy_model_2018_2019, "Model 2019 - 2020" = tidy_model_2019_2020, "Model 2020 - 2021" = tidy_model_2020_2021, "Model 2021 - 2022" = tidy_model_2021_2022) %>% rename( state_year_coefficient = estimate, year = term)

#Changing into values into the years

Coefficients_visualizations_table <- Coefficients_visualizations_table %>%
  mutate(year = case_when( year == "stateMO:year2012"~ 2012,year == "stateMO:year2013" ~ 2013, year == "stateMO:year2014" ~ 2014, year == "stateMO:year2015" ~ 2015, year == "stateMO:year2016" ~ 2016, year == "stateMO:year2017" ~ 2017, year == "stateMO:year2018" ~ 2018, year == "stateMO:year2019" ~ 2019, year == "stateMO:year2020" ~ 2020, year == "stateMO:year2021" ~ 2021, year == "stateMO:year2022" ~ 2022
          ))

# Add min wage data into the table

Coefficients_visualizations_table <- Coefficients_visualizations_table %>%
  mutate(mw_increase = c(0 , 0.10 , 0.15 , 0.15 , 0 , 0.05 , 0.15 , 0.75 , 0.85 , 0.85 , 0.85 ))

#Join Confints into the Coefficients Visualizations Table

Master_Table <- left_join(
x = Coefficients_visualizations_table, 
y = confints, 
by = "year"
) %>%
  rename(lwr = "2.5 %", upr = "97.5 %")

```

```{r, include=FALSE}

# Reshape the data into a longer format
reshaped_data <- Master_Table %>%
  mutate(mw_increase = mw_increase*(1/0.0025)) %>%
  pivot_longer(
    cols = c(state_year_coefficient, mw_increase),
    names_to = "Variable",
    values_to = "Value"
  )

# Plotting the reshaped data
col_plot <- ggplot(reshaped_data, aes(x = year, y = Value, fill = Variable)) +
  geom_col(position = "dodge", alpha = 0.7) +
  geom_errorbar(aes(ymin = lwr, ymax = upr), 
                position = position_nudge( x = 0.23), width = 0.4) +
  labs(
    title = "Employment and Minimum Wage Change in Missouri, 2012 - 2022",
    x = "Year",
    y = "Values",
    fill = " "
  ) + 
  scale_fill_manual(values = c("state_year_coefficient" = "blue", "mw_increase" = "red"), 
                    breaks = c("state_year_coefficient", "mw_increase"),
                    labels = c("Employment\nChange", "MW Increase")) +
  scale_y_continuous(
    name = "Employment Change Coefficient",
    sec.axis = sec_axis(~. * .0025, name = "MW Increase")
  ) + 
  theme_minimal() + 
  scale_x_continuous(breaks = 2012:2022)
  
col_plot

# ggsave(filename = "Column_Plot.png", plot = col_plot, dpi = "retina", width = 10.4, height = 4.81)
```


```{r}
library(stargazer)
```

```{r}
table_models <- list(model_2011_2012, model_2012_2013, model_2013_2014, model_2014_2015, model_2015_2016, model_2016_2017, model_2017_2018, model_2018_2019, model_2019_2020, model_2020_2021, model_2021_2022)
```

```{r}
model_names <- c("Model 2011-2012", "Model 2012-2013", "Model 2013-2014", "Model 2014-2015", "Model 2015-2016", "Model 2016-2017", "Model 2017-2018", "Model 2018-2019", "Model 2019-2020", "Model 2020-2021", "Model 2021-2022")

# Extract coefficients for each model
coefficients_list <- lapply(table_models, coef)

# Create a new list to store consolidated coefficients
consolidated_coefficients <- list()

# Loop through each year
for (year in unique(gsub(".*year(.*)", "\\1", names(coefficients_list[[1]])))) {
  # Extract coefficients for the specific year
  year_coefficients <- lapply(coefficients_list, function(model) model[grep(paste0("year", year), names(model))])
  
  # Consolidate coefficients for the specific year
  consolidated_coefficients[[year]] <- do.call(cbind, year_coefficients)
}
```

```{r, results="asis"}
# Customize stargazer options
stargazer(
  table_models1,
  title = "Regression Results",
  type = 'latex',
  align = TRUE,                  # Align coefficient names to the left
  dep.var.caption = "Dependent variable: \\textbf{emplvl\\_limited}",  # Bold dependent variable in the caption
  column.labels = model_names,   # Model labels
  covariate.labels = names(consolidated_coefficients[[1]]),  # Custom order of variables
  digits = 3,                    # Number of decimal places
  star.cutoffs = c(0.1, 0.05, 0.01),  # Customize significance stars
  notes = "\\textit{Note:} $^{*}p<0.1; ^{**}p<0.05; ^{***}p<0.01",  # Custom note
  omit = names(consolidated_coefficients[[1]])[-1]  # Omit redundant coefficients
)
```

```{r}

# Trying with the three year pairs instead

# table_models_2 <- list(model_2011_2012, model_2012_2013, model_2013_2014)


# stargazer(table_models_2)
```


